site_name: "Origins: Math Documentation"
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Changelog: changelog.md
  - Theorem and Usage: theorem_and_usage.md
  - General Types:
    - Power Types: types/power_types.md
    - Data Types: types/data_types.md
  - Action Types:
    - Entity Action Types: types/entity_action_types.md
    - Bi-entity Action Types: types/bientity_action_types.md
  - Condition Types:
    - Entity Condition Types: types/entity_condition_types.md
  - Miscellaneous:
    - Commands: misc/commands.md
  - Extra Notes:
    - Resource-backed fields: notes/resource_backed_fields.md
  - Add-On Guides:
    - Creating Resource value bridges: addon/creating_resource_value_bridges.md
    - Value Providers API: addon/value_providers_api.md
  - Experiments:
    - Extended Compatibility through ASM: experiments/extended_compatibility_through_asm.md

theme: readthedocs
markdown_extensions:
  - toc:
      separator: "_"
  - admonition
plugins:
  - search
  - autorefs
  - alias
  - categories
extra_css:
  - styles/style.css